- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name:
      - git
      - curl
      - unzip
      - ca-certificates
    state: present

- name: Add NodeSource Node.js 20 repo
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Node.js 20
  apt:
    name: nodejs
    state: present

- name: Verify Node.js version
  command: node -v
  register: node_version

- debug:
    msg: "Installed Node version: {{ node_version.stdout }}"

- name: Install Ansible
  apt:
    name: ansible
    state: present

- name: Allow Jenkins passwordless sudo
  copy:
    dest: /etc/sudoers.d/jenkins
    content: "jenkins ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"
